---
- name: Add computer object to domain group
  hosts: all
  gather_facts: no

  tasks:
    - name: Add computer to domain group
      win_shell: |
        Remove-ADGroupMember -Identity "{{ domain_group }}" -Members "{{ computer_name }}$" -Confirm:$false
      args:
        executable: powershell

    - name: Store computer_name for workflow
      set_stats:
        data:
          computer_name: "{{ computer_name }}"
