---
- name: Check if computer is member of domain group and show message
  hosts: all
  gather_facts: no
  vars:
    domain_group: "TestDimasGroup"
    computer_name: "RND1CLIENT02$"
  tasks:
    - name: Check computer membership in domain group (output JSON)
      win_shell: |
        $exists = (Get-ADGroupMember -Identity "{{ domain_group }}" | Where-Object { $_.SamAccountName -eq "{{ computer_name }}" })
        $result = $exists -ne $null
        $result | ConvertTo-Json
      args:
        executable: powershell
      register: check_group_member

    - name: Set membership fact
      set_fact:
        is_member: "{{ check_group_member.stdout | from_json }}"

    - name: Show success message if computer is in group
      debug:
        message: "Success"
      when: is_member

    - name: Show failed message if computer is NOT in group
      debug:
        msg: "Failed, Hostname tidak ada pada Group Domain."
      when: not is_member
