---
- name: Remove All Members
  hosts: all
  gather_facts: no

  tasks:
  - name: Remove All Members
    win_shell: |
      Import-Module "$($ENV:SMS_ADMIN_UI_PATH)\..\ConfigurationManager.psd1"
      cd "CAS:"

      $collectionName = "Pilot 1"

      $collection = Get-CMDeviceCollection -Name $collectionName

      # Get all direct members (Resource IDs)
      $members = Get-CMDeviceCollectionDirectMembershipRule -CollectionId $collection.CollectionID

      foreach ($member in $members) {
          Write-Host "Removing ResourceID $($member.ResourceID) from collection $collectionName"
          Remove-CMDeviceCollectionDirectMembershipRule -CollectionId $collection.CollectionID -ResourceId $member.ResourceID -Force
      }

      Invoke-CMDeviceCollectionUpdate -Name $collectionName
