---
- name: Remove All Members
  hosts: all
  gather_facts: no

  tasks:
  - name: Remove All Members
    ansible.windows.win_shell: 'powershell.exe -File G:\APPS\File_Script\Remove_All_Member_Collection.ps1'
