---
- name: Run SCCM script to specific device
  hosts: all
  gather_facts: no
  vars:
    sccm_site_code: "CAS"
    sccm_device_name: "RND1CLIENT01"
    sccm_script_name: "TestScript"
  tasks:
    - name: Run script on specific device
      win_shell: |
        Import-Module "$($ENV:SMS_ADMIN_UI_PATH)\..\ConfigurationManager.psd1"
        cd "{{ sccm_site_code }}:"
        $device = Get-CMDevice -Name "{{ sccm_device_name }}"
        Invoke-CMRunScript -Device $device -ScriptName "{{ sccm_script_name }}"
      args:
        executable: powershell
      register: sccm_script_result
