---
- name: Update Version String
  hosts: all
  gather_facts: no

  tasks:
  - name: update version string
    ansible.windows.win_shell: 'powershell.exe -File G:\APPS\File_Script\Update_Version_String.ps1'
